# Generated by Django 5.0.6 on 2024-06-13 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='moviemodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40)),
                ('release_date', models.DateField()),
                ('reviewed_on', models.DateField()),
                ('story', models.TextField()),
                ('rating', models.DecimalField(decimal_places=1, max_digits=2)),
                ('review', models.TextField()),
            ],
        ),
    ]
