# Generated by Django 5.0.6 on 2024-06-13 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proj_app', '0002_moviemodel_movie_poster'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviemodel',
            name='director',
            field=models.CharField(default='Unknown', max_length=20),
        ),
    ]
