# Generated by Django 5.0.6 on 2024-06-13 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proj_app', '0004_moviemodel_trailer_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviemodel',
            name='director',
            field=models.CharField(max_length=20),
        ),
    ]
