# Generated by Django 5.0.6 on 2024-06-17 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proj_app', '0012_alter_moviemodel_sample'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviemodel',
            name='sample',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
