# Generated by Django 5.0.6 on 2024-06-17 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proj_app', '0014_alter_moviemodel_sample'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moviemodel',
            name='sample',
        ),
    ]
