# Generated by Django 5.0.6 on 2024-06-18 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proj_app', '0016_registermodel2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registermodel2',
            name='phno',
        ),
        migrations.AddField(
            model_name='registermodel2',
            name='city',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
