# Generated by Django 5.0.6 on 2024-06-21 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proj_app', '0017_remove_registermodel2_phno_registermodel2_city'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registermodel2',
            name='city',
        ),
        migrations.AddField(
            model_name='registermodel2',
            name='ph_no',
            field=models.PositiveBigIntegerField(null=True),
        ),
    ]
